// <auto-generated />
using System;
using FolhaPagamento.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FolhaPagamento.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20221006224515_AddEmailSalarioTableFu")]
    partial class AddEmailSalarioTableFu
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.17");

            modelBuilder.Entity("FolhaPagamento.Models.Folha", b =>
                {
                    b.Property<int>("FolhaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FuncionarioId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id");

                    b.Property<int>("impostoFgts")
                        .HasColumnType("INTEGER");

                    b.Property<int>("impostoInss")
                        .HasColumnType("INTEGER");

                    b.Property<int>("impostoRenda")
                        .HasColumnType("INTEGER");

                    b.Property<int>("quantidadeHoras")
                        .HasColumnType("INTEGER");

                    b.Property<int>("salarioBruto")
                        .HasColumnType("INTEGER");

                    b.Property<int>("salarioLiquido")
                        .HasColumnType("INTEGER");

                    b.Property<int>("valorhora")
                        .HasColumnType("INTEGER");

                    b.HasKey("FolhaId");

                    b.HasIndex("FuncionarioId");

                    b.ToTable("Folhas");
                });

            modelBuilder.Entity("FolhaPagamento.Models.Funcionario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Salario")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Funcionarios");
                });

            modelBuilder.Entity("FolhaPagamento.Models.Folha", b =>
                {
                    b.HasOne("FolhaPagamento.Models.Funcionario", "Funcionario")
                        .WithMany()
                        .HasForeignKey("FuncionarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Funcionario");
                });
#pragma warning restore 612, 618
        }
    }
}
